terafoundation:
  connectors:
    elasticsearch-next:
      es7:
        node:
          - "http://elasticsearch7-master:9200"
      os2:
        node:
          - "http://opensearch2:9200"
  environment: development
  log_level: debug
  workers: 1
  prom_metrics_enabled: true
  prom_metrics_port: 3333
  prom_metrics_add_default: true
  prom_metrics_display_url: ""
terasliceJobSettingsController:
  cluster: test1
  connections:
    store:
      connector: es7
      index: percent-to-keep
      document_id: noaa-2025-01-sample-v1
    sample:
      connector: os2
      daily_index_prefix: noaa-2025-01-sample-v1
      date_delimiter: "."
  window_ms: 60000
  target_rate: 0.002219
  minimum_percent: 25
  initial_percent_kept: 75
  pid_constants: { proportional: 0.1, integral: 0.01, derivative: 0.1 }
  